### ISSUE TITLE
Plugin version not updated in Roundcube plugins site

### ISSUE THREAD

**Issue by dsoares** [messagerie-melanie2/Roundcube-Plugin-JQuery-Mobile#3]
Hi,

You released a new version here in Github but https://plugins.roundcube.net/packages/melanie2/mobile wasn't updated. Maybe you forgot to [create the hook](https://plugins.roundcube.net/about#how-to-update-packages) ?
Thanks for the plugin!

**Comment by tpayen** [comment]
Hi,
Hmm, for me the release version is correct : for jquery_mobile 1.1 on Github, 1.1 on https://plugins.roundcube.net/packages/melanie2/jquery_mobile
for mobile plugin 0.4.8 on Github, 0.4.8 on https://plugins.roundcube.net/packages/melanie2/mobile
Where did you see a difference between the versions ?

**Comment by dsoares** [comment]
I'm so sorry, it was a distraction! I checked the github page for jquery_mobile 1.1 then went to roundcube plugins page, maybe i used the browser auto-complete URL and saw the mobile 0.4.8 page. 
Everything is OK!
